In [1]:
import os
import numpy as np
import pandas as pd
import geopandas as gpd
import rasters as rt
from rasters import MultiPoint
from PTJPLSM import PTJPLSM, process_PTJPLSM_table
from PTJPL import load_Topt, load_fAPARmax
from soil_capacity_wilting import load_field_capacity
from soil_capacity_wilting import load_wilting_point
from gedi_canopy_height import load_canopy_height
from ECOv002_calval_tables import load_combined_eco_flux_ec_filtered, load_metadata_ebc_filt, load_calval_table

In [2]:
repo_root = os.path.dirname(os.getcwd())
package_dir = os.path.join(repo_root, 'PTJPLSM')
generated_input_table_filename = os.path.join(package_dir, "ECOv002-cal-val-PT-JPL-SM-inputs.csv")
generated_output_table_filename = os.path.join(package_dir, "ECOv002-cal-val-PT-JPL-SM-outputs.csv")

In [3]:
model_inputs_gdf = load_calval_table()
model_inputs_gdf

Unnamed: 0      ID vegetation climate    STICinst   BESSinst  \
0              0  US-NC3        ENF     Cfa  270.345200   78.53355   
1              1  US-Mi3        CVM     Dfb  232.141600  229.20093   
2              2  US-Mi3        CVM     Dfb  356.355740  335.23154   
3              3  US-Mi3        CVM     Dfb  332.938400  326.68680   
4              4  US-Mi3        CVM     Dfb  286.854030  237.21654   
...          ...     ...        ...     ...         ...        ...   
1060        1060  US-xAE        GRA     Cfa   70.923310  172.37459   
1061        1061  US-xAE        GRA     Cfa  116.543190  121.81641   
1062        1062  US-xAE        GRA     Cfa  129.880100    0.00000   
1063        1063  US-xAE        GRA     Cfa    2.707851  140.38632   
1064        1064  US-xAE        GRA     Cfa  303.242950    0.00000   

       MOD16inst  PTJPLSMinst      ETinst  ETinstUncertainty  ...  \
0     392.851840   307.021970  487.383423         118.916280  ...   
1     640.118470   375.089300  106.825577         167.919460  ...   
2     625.661700   284.686250         NaN         132.936340  ...   
3     624.254330   251.414490  178.827545         141.132420  ...   
4     511.082180   228.520170  154.791626         114.809410  ...   
...          ...          ...         ...                ...  ...   
1060   81.645230    15.282976         NaN          56.385185  ...   
1061   65.469320    22.186659         NaN          40.509410  ...   
1062  118.777240    55.343586         NaN          52.403820  ...   
1063  126.490524    40.434025         NaN          57.769722  ...   
1064  271.749480   119.763630  190.823303         122.092445  ...   

             EndDate  LE_count  closure_ratio                  geometry  \
0       1/1/22 05:00      9576           1.02    POINT (-76.656 35.799)   
1     12/28/19 04:00     12170           0.92   POINT (-80.637 41.8222)   
2     12/28/19 04:00     12170           0.92   POINT (-80.637 41.8222)   
3     12/28/19 04:00     12170           0.92   POINT (-80.637 41.8222)   
4     12/28/19 04:00     12170           0.92   POINT (-80.637 41.8222)   
...              ...       ...            ...                       ...   
1060   12/1/22 00:00     29615           0.60  POINT (-99.0588 35.4106)   
1061   12/1/22 00:00     29615           0.60  POINT (-99.0588 35.4106)   
1062   12/1/22 00:00     29615           0.60  POINT (-99.0588 35.4106)   
1063   12/1/22 00:00     29615           0.60  POINT (-99.0588 35.4106)   
1064   12/1/22 00:00     29615           0.60  POINT (-99.0588 35.4106)   

                 time_UTC    ST_K   ST_C       Ta_C   SWin_Wm2  emissivity  
0     2019-10-02 19:09:40  305.10  31.95  32.658920  545.51056       0.948  
1     2019-06-23 18:17:17  304.34  31.19  24.227982  848.34390       0.952  
2     2019-06-27 16:35:42  304.06  30.91  26.178862  838.81160       0.972  
3     2019-06-30 15:44:10  301.80  28.65  22.527096  851.72480       0.974  
4     2019-07-01 14:53:48  303.18  30.03  23.280691  702.55160       0.960  
...                   ...     ...    ...        ...        ...         ...  
1060  2021-12-11 16:01:12  278.78   5.63   3.815752  286.84660       0.980  
1061  2022-03-25 22:45:31  293.28  20.13  19.266186  290.87400       0.976  
1062  2022-04-12 22:53:09  301.94  28.79  32.110336  352.19530       0.976  
1063  2022-04-14 14:45:37  290.72  17.57  10.464681  420.67880       0.976  
1064  2022-04-20 19:38:47  314.76  41.61  30.316103  781.84110       0.978  

[1065 rows x 77 columns]

In [4]:
# extract array of x and array of y coordinates from data frame geometry
x_coords = model_inputs_gdf.geometry.x
y_coords = model_inputs_gdf.geometry.y
tower_points = MultiPoint(x=x_coords, y=y_coords)
tower_points

MULTIPOINT ((-76.656 35.799), (-80.637 41.8222), (-80.637 41.8222), (-80.637 41.8222), (-80.637 41.8222), (-80.637 41.8222), (-75.9038 35.7879), (-80.6313 41.7727), (-80.6313 41.7727), (-80.6313 41.7727), (-80.6313 41.7727), (-80.6313 41.7727), (-90.3004 45.9793), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-122.3303 45.7624), (-71.7181 43.9397), (-71.7181 43.9397), (-71.7181 43.9397), (-71.7181 43.9397), (-71.7181 43.9397), (-71.7181 43.9397), (-71.7181 43.9397), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6078 44.3233), (-121.6

In [5]:
Topt_C = load_Topt(geometry=tower_points)
model_inputs_gdf["Topt_C"] = Topt_C
Topt_C

array([10.09,  1.39,  1.39, ...,  7.99,  7.99,  7.99], shape=(1065,))

In [6]:
fAPARmax = load_fAPARmax(geometry=tower_points)
model_inputs_gdf["fAPARmax"] = fAPARmax
fAPARmax

array([0.4659, 0.4865, 0.4865, ..., 0.3387, 0.3387, 0.3387], shape=(1065,))

In [7]:
canopy_height_meters = load_canopy_height(geometry=tower_points)
model_inputs_gdf["canopy_height_meters"] = canopy_height_meters
canopy_height_meters

array([20.64290228,  0.        ,  0.        , ...,  0.        ,
        0.        ,  0.        ], shape=(1065,))

In [8]:
field_capacity = load_field_capacity(geometry=tower_points)
model_inputs_gdf["field_capacity"] = field_capacity
field_capacity

array([0.24, 0.31, 0.31, ..., 0.28, 0.28, 0.28], shape=(1065,))

In [9]:
wilting_point = load_wilting_point(geometry=tower_points)
model_inputs_gdf["wilting_point"] = wilting_point
wilting_point

array([0.11, 0.14, 0.14, ..., 0.13, 0.13, 0.13], shape=(1065,))

In [10]:
model_inputs_gdf

Unnamed: 0      ID vegetation climate    STICinst   BESSinst  \
0              0  US-NC3        ENF     Cfa  270.345200   78.53355   
1              1  US-Mi3        CVM     Dfb  232.141600  229.20093   
2              2  US-Mi3        CVM     Dfb  356.355740  335.23154   
3              3  US-Mi3        CVM     Dfb  332.938400  326.68680   
4              4  US-Mi3        CVM     Dfb  286.854030  237.21654   
...          ...     ...        ...     ...         ...        ...   
1060        1060  US-xAE        GRA     Cfa   70.923310  172.37459   
1061        1061  US-xAE        GRA     Cfa  116.543190  121.81641   
1062        1062  US-xAE        GRA     Cfa  129.880100    0.00000   
1063        1063  US-xAE        GRA     Cfa    2.707851  140.38632   
1064        1064  US-xAE        GRA     Cfa  303.242950    0.00000   

       MOD16inst  PTJPLSMinst      ETinst  ETinstUncertainty  ...    ST_K  \
0     392.851840   307.021970  487.383423         118.916280  ...  305.10   
1     640.118470   375.089300  106.825577         167.919460  ...  304.34   
2     625.661700   284.686250         NaN         132.936340  ...  304.06   
3     624.254330   251.414490  178.827545         141.132420  ...  301.80   
4     511.082180   228.520170  154.791626         114.809410  ...  303.18   
...          ...          ...         ...                ...  ...     ...   
1060   81.645230    15.282976         NaN          56.385185  ...  278.78   
1061   65.469320    22.186659         NaN          40.509410  ...  293.28   
1062  118.777240    55.343586         NaN          52.403820  ...  301.94   
1063  126.490524    40.434025         NaN          57.769722  ...  290.72   
1064  271.749480   119.763630  190.823303         122.092445  ...  314.76   

       ST_C       Ta_C   SWin_Wm2  emissivity  Topt_C  fAPARmax  \
0     31.95  32.658920  545.51056       0.948   10.09    0.4659   
1     31.19  24.227982  848.34390       0.952    1.39    0.4865   
2     30.91  26.178862  838.81160       0.972    1.39    0.4865   
3     28.65  22.527096  851.72480       0.974    1.39    0.4865   
4     30.03  23.280691  702.55160       0.960    1.39    0.4865   
...     ...        ...        ...         ...     ...       ...   
1060   5.63   3.815752  286.84660       0.980    7.99    0.3387   
1061  20.13  19.266186  290.87400       0.976    7.99    0.3387   
1062  28.79  32.110336  352.19530       0.976    7.99    0.3387   
1063  17.57  10.464681  420.67880       0.976    7.99    0.3387   
1064  41.61  30.316103  781.84110       0.978    7.99    0.3387   

      canopy_height_meters  field_capacity  wilting_point  
0                20.642902            0.24           0.11  
1                 0.000000            0.31           0.14  
2                 0.000000            0.31           0.14  
3                 0.000000            0.31           0.14  
4                 0.000000            0.31           0.14  
...                    ...             ...            ...  
1060              0.000000            0.28           0.13  
1061              0.000000            0.28           0.13  
1062              0.000000            0.28           0.13  
1063              0.000000            0.28           0.13  
1064              0.000000            0.28           0.13  

[1065 rows x 82 columns]

In [11]:
model_inputs_gdf.keys()

Index(['Unnamed: 0', 'ID', 'vegetation', 'climate', 'STICinst', 'BESSinst',
       'MOD16inst', 'PTJPLSMinst', 'ETinst', 'ETinstUncertainty', 'PET', 'Rn',
       'ESI', 'RH', 'Ta', 'LST', 'SM', 'NDVI', 'NDVI-UQ', 'albedo',
       'albedo-UQ', 'LST_err', 'view_zenith', 'Rg', 'EmisWB', 'time_utc',
       'solar_time', 'solar_hour', 'local_time', 'LE', 'LE_filt', 'LEcorr25',
       'LEcorr50', 'LEcorr75', 'LEcorr_ann', 'H_filt', 'Hcorr25', 'Hcorr50',
       'Hcorr75', 'Hcorr_ann', 'NETRAD_filt', 'G_filt', 'SM_surf', 'SM_rz',
       'AirTempC', 'SW_IN', 'RH_percentage', 'ESIrn_STIC', 'ESIrn_PTJPLSM',
       'ESIrn_MOD16', 'ESIrn_BESS', 'ESIrn_Unc_ECO', 'ESIrn_LEcorr50', 'JET',
       'eco_time_utc', 'Site Name', 'Date-Time', 'Site ID', 'Name', 'Lat',
       'Long', 'Elev', 'Clim', 'Veg', 'MAT', 'MAP', 'StartDate', 'EndDate',
       'LE_count', 'closure_ratio', 'geometry', 'time_UTC', 'ST_K', 'ST_C',
       'Ta_C', 'SWin_Wm2', 'emissivity', 'Topt_C', 'fAPARmax',
       'canopy_height_meters

In [12]:
model_inputs_gdf.albedo

0       0.215445
1       0.117238
2       0.117280
3       0.084629
4       0.120526
          ...   
1060    0.092853
1061    0.111844
1062    0.106782
1063    0.106775
1064    0.113165
Name: albedo, Length: 1065, dtype: float64

In [13]:
results = process_PTJPLSM_table(model_inputs_gdf)
results

[2025-08-13 18:17:34 INFO] starting PT-JPL-SM table processing
[2025-08-13 18:17:34 INFO] started extracting geometry from PT-JPL-SM input table
[2025-08-13 18:17:34 INFO] completed extracting geometry from PT-JPL-SM input table
[2025-08-13 18:17:34 INFO] started extracting time from PT-JPL-SM input table
[2025-08-13 18:17:34 INFO] completed extracting time from PT-JPL-SM input table
[2025-08-13 18:17:34 INFO] starting PT-JPL-SM model run
[2025-08-13 18:17:34 INFO] using given optimum temperature (Topt_C)
[2025-08-13 18:17:34 INFO] variable Topt_C min: 0.000 mean: 8.174 max: 23.210 nan: 0.00% (nan)
[2025-08-13 18:17:34 INFO] variable fAPARmax min: 0.233 mean: 0.382 max: 0.624 nan: 0.00% (nan)
[2025-08-13 18:17:34 INFO] using given air temperature (Ta_C)
[2025-08-13 18:17:34 INFO] variable Ta_C min: -14.605 mean: 22.322 max: 39.710 nan: 0.00% (nan)
[2025-08-13 18:17:34 INFO] using given relative humidity (RH)
[2025-08-13 18:17:34 INFO] variable RH min: 0.273 mean: 0.427 max: 0.984 nan: 

Unnamed: 0      ID vegetation climate    STICinst   BESSinst  \
0              0  US-NC3        ENF     Cfa  270.345200   78.53355   
1              1  US-Mi3        CVM     Dfb  232.141600  229.20093   
2              2  US-Mi3        CVM     Dfb  356.355740  335.23154   
3              3  US-Mi3        CVM     Dfb  332.938400  326.68680   
4              4  US-Mi3        CVM     Dfb  286.854030  237.21654   
...          ...     ...        ...     ...         ...        ...   
1060        1060  US-xAE        GRA     Cfa   70.923310  172.37459   
1061        1061  US-xAE        GRA     Cfa  116.543190  121.81641   
1062        1062  US-xAE        GRA     Cfa  129.880100    0.00000   
1063        1063  US-xAE        GRA     Cfa    2.707851  140.38632   
1064        1064  US-xAE        GRA     Cfa  303.242950    0.00000   

       MOD16inst  PTJPLSMinst      ETinst  ETinstUncertainty  ...  \
0     392.851840   307.021970  487.383423         118.916280  ...   
1     640.118470   375.089300  106.825577         167.919460  ...   
2     625.661700   284.686250         NaN         132.936340  ...   
3     624.254330   251.414490  178.827545         141.132420  ...   
4     511.082180   228.520170  154.791626         114.809410  ...   
...          ...          ...         ...                ...  ...   
1060   81.645230    15.282976         NaN          56.385185  ...   
1061   65.469320    22.186659         NaN          40.509410  ...   
1062  118.777240    55.343586         NaN          52.403820  ...   
1063  126.490524    40.434025         NaN          57.769722  ...   
1064  271.749480   119.763630  190.823303         122.092445  ...   

      wilting_point      Rn_Wm2       G_Wm2  Rn_soil_Wm2  LE_soil_Wm2  \
0              0.11  395.386594   51.199585   108.445418    58.201498   
1              0.14  641.736047   81.090155   242.327021   148.708756   
2              0.14  654.338979   84.048662   265.452689   171.730760   
3              0.14  678.553376   70.192914   220.223334   134.990066   
4              0.14  516.680516   58.699784   163.457363    95.318041   
...             ...         ...         ...          ...          ...   
1060           0.13  162.251159    4.078005   120.709633     1.660663   
1061           0.13  166.366277   15.458719   132.038087     2.481284   
1062           0.13  256.512330   33.685416   186.580017     2.096448   
1063           0.13  246.524236   19.755022   179.019182     1.670621   
1064           0.13  542.600776  104.077863   396.978125     6.298751   

      Rn_canopy_Wm2     PET_Wm2  LE_canopy_Wm2  LE_interception_Wm2  \
0        286.941176  349.932890     226.051334            28.734376   
1        399.409026  517.083672     222.315394            16.280228   
2        388.886290  539.879902      96.551225            54.990754   
3        458.330042  547.373133     108.049874            62.517459   
4        353.223153  416.712815     118.816031            34.312196   
...             ...         ...            ...                  ...   
1060      41.541526   91.824890      13.658025             0.591490   
1061      34.328190  128.742933      19.782974             0.730644   
1062      69.932313  225.364587      58.572453             0.958892   
1063      67.505054  160.182155      39.163293             0.708102   
1064     145.622651  435.565400     112.621752             3.131581   

          LE_Wm2  
0     312.987207  
1     387.304378  
2     323.272740  
3     305.557399  
4     248.446268  
...          ...  
1060   15.910178  
1061   22.994902  
1062   61.627793  
1063   41.542015  
1064  122.052084  

[1065 rows x 91 columns]

In [14]:
model_inputs_gdf.to_csv(generated_input_table_filename, index=False)

In [15]:
results.to_csv(generated_output_table_filename, index=False)